app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class User(UserMixin,db.Model):
    __tablename__='users'

    id = db.Column(db.Integer,primary_key=True)
    username= db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True , index=True)
    bio= db.Column(db.String(255))
    profile_pic_path = db.Column(db.String(255))
    pass_secure=db.Column(db.String(255))
    pitches= db.relationship('Pitch',backref='user', lazy='dynamic')
    comments = db.relationship('Comment',backref='user' ,lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Pitch(db.Model):
   __tablename__ = 'pitches'

   id = db.Column(db.Integer,primary_key = True)
   user_id= db.Column(db.Integer,db.ForeignKey('users.id'))
   content = db.Column(db.String(255))
   comments = db.relationship('Comment',backref='pitch' ,lazy='dynamic')
   category = db.Column(db.String(255))
   upvotes = db.Column(db.Integer)
   downvotes = db.Column(db.Integer)


   def save_pitch(self):
        db.session.add(self)
        db.session.commit()

   @classmethod
   def clear_pitches(cls):
        Pitch.all_pitches.clear()

   @classmethod
   def get_pitche(cls,id):
        pitche = Pitch.query.filter_by(id=id).all()
        return pitche
    
   @classmethod
   def get_pitches(cls):
       pitches = Pitch.query.filter_by().all()
       return pitches

   @classmethod
   def upvotess(cls,id):
       pitch=Pitch.query.filter_by(id=id).first()
       pitch.upvotes=0
       upvotes=pitch.upvotes+1
       return upvotes

   @classmethod
   def downvotess(cls,id):
       pitch=Pitch.query.filter_by(id=id).first()
       pitch.downvotes=0
       downvotes=pitch.downvotes-1
       return downvotes




class Comment(db.Model):
    __tablename__= 'comments'
    
    id= db.Column(db.Integer,primary_key= True)
    content = db.Column(db.String(255))
    user_id= db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))


    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def clear_comments(cls):
        Comment.all_comments.clear()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(pitch_id=id).all()
        return comments

    @classmethod
    def get_commentss(cls,id):
        comments = Comment.query.filter_by(user_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class CommentForm(FlaskForm):
   
#    title = StringField('Comment title',validators=[Required()])
   comment = TextAreaField('pitch comment', validators=[Required()])
   submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class AddPitchForm(FlaskForm):
    category= SelectField('Category:',choices=[('pickup-lines','Pickup lines'),('Interview-pitches','interview pitches'),('promotion-pitches','Promotion pitches')])
    content=TextAreaField('Pitch',validators = [Required()])
    submit=SubmitField('SUBMIT')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES
mail = Mail()
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
#........
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # configure UploadSet
    configure_uploads(app,photos)
  
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for, abort
from . import main
from .forms import UpdateProfile,CommentForm,AddPitchForm
from .. import db,photos
from ..models import Comment,Pitch,User
from flask_login import login_required, current_user
# from flask_fontawesome import FontAwesome

@main.route('/')
def index():
  title="Home| 60 seconds pitch"
  # all_pitches = Pitch.get_pitches()
  
  return render_template('index.html',title=title)

@main.route('/pitch/new', methods = ['GET', 'POST'])
@login_required
def add_pitch():
    form = AddPitchForm()
    
    if form.validate_on_submit():
        category = form.category.data

        pitch = form.content.data

        new_pitch = Pitch(content=pitch, category = category,upvotes=0,downvotes=0 ,user=current_user)
        new_pitch.save_pitch()

        return redirect(url_for('main.index'))

    # all_pitches = Pitch.get_pitches()

    title = 'Add Pitch| 60 seconds pitch'    
    return render_template('pitches.html', title = title, pitch_form = form,user=current_user)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))
# 
@main.route('/new/comment/<int:id>', methods = ['GET','POST'])
@login_required
def add_comment(id):
  pitch=Pitch.query.filter_by(id=id).first()
  if pitch is None:
    abort(404)

  form=CommentForm()
  if form.validate_on_submit():
     comment=form.comment.data
     new_comment=Comment(content=comment ,pitch=pitch ,user=current_user)
     db.session.add(new_comment)  
     db.session.commit() 

     return redirect(url_for('main.index'))
  return render_template('comment.html', comment_form=form)

@main.route('/pitch/<int:id>')
def single_pitch(id):
    pitch=Pitch.query.filter_by(id=id).first()
    comments=Comment.get_comments(id=id)
    return render_template('pitch.html',pitch=pitch,comments=comments)

@main.route('/upvotes/<int:id>')
def upvoting(id):
    pitch1=Pitch.query.filter_by(id=id).first()
    pitch1.upvotes=Pitch.upvote(pitch1.id)
    return redirect(url_for('main.single_pitch',id=pitch1.id))

@main.route('/categories')
def categories():
    title="Categories"

    return render_template('categories.html')

@main.route('/category/pickup')
def pickup():
    title="60 seconds|Pickup"
    pitches=Pitch.query.filter_by(category='pickup-lines').all()
    return render_template('pickup.html',pitches=pitches)

@main.route('/category/interview')
def interview():
    title="60 seconds|Interview"
    pitches=Pitch.query.filter_by(category='Interview-pitches').all()
    return render_template('interview.html',pitches=pitches)
        
@main.route('/category/promotion')
def promotion():
    title="60 seconds|Promotion"
    pitches=Pitch.query.filter_by(category='promotion-pitches').all()
    return render_template('promotion.html',pitches=pitches)
    

    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body style="background-color: #6D4C41   ">
    
</body>
</html>

{% extends 'bootstrap/base.html'%}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/categories.html
{% extends 'base.html'%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{%block content %}
<div class="container">
<h1>Categories</h1>
  <a href="/category/pickup" class="btn btn-primary btn-lg">Pickup lines category</a>
  <a href="/category/interview" class="btn btn-primary btn-lg">Interview pitch category</a>
  <a href="/category/promotion" class="btn btn-primary btn-lg">Promotion category</a>
</div>
{%endblock%}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">
{{wtf.quick_form(comment_form)}}

<!-- {{ macro.displayPitches(pitches)}} -->
</div>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h2>OOps, look like you are facing an issue can't find the page requested</h2>
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{{ fontawesome_html() }}
{% import "bootstrap/wtf.html" as wtf %}

<!-- Styles block -->

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
{% if title %}
<title> {{ title }}</title>
{% else %}
<title> Welcome to 60 seconds pitchApp</title>
{% endif %}

{%block content %}
<div class="jumbtron">
    <h1 id="big" style="color:#EEEEEE ; text-align: center;font-size:90px;font-style:oblique" >Welcome To 60 Seconds PitchApp</h1>
</div>



<div class="container">

    {{ macro.displayPitches(pitches)}}<br>
    <a href="/pitch/new" class="btn btn-primary">Add Pitch</a>
</div>


{% endblock %}

app/templates/interview.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{%block content%}
<h2>Interview</h2>
{{macro.displayPitches(pitches)}}<br>
{%endblock%}

app/templates/macros.html
{% macro displayPitches(pitches) %}

{% for pitch in pitches %}
   {% if pitch.user.profile_pic_path %}
   <div class="container rr" >
    <img src="static/photos/no_dp.png" alt="Display image" height='50' width='50'>
    <p class="username">{{pitch.user.username}}</p>

  <a href="/pitch/{{pitch.id}}" class='pitch col-md-6'>{{pitch.content}}</a><br>
  <button href="">Upvote</button>
  <button>Downvote</button>
  
   <a href="/new/comment/{{pitch.id}}" class="btn btn-primary">Add comment</a>
  </div>
  {%else %}
  <div class="container rr">
   <img src="static/photos/no_dp.png" alt="">
   <p class="name">{{pitch.user.username}}</p>
   <a href="/pitch/{{pitch.id}}" class='pitch'>{{pitch.content}}</a><br>

  <button>Upvote</button>
  <button>Downvote</button>
  <a href="/new/comment/{{pitch.id}}" class="btn btn-primary">Add comment</a>
</div>
  {%endif%}

  {%endfor%}
  {%endmacro%}

{% macro displayComments(comments) %}
{% for comment in comments %}
{% if comment.user.profile_pic_path %}
<div class="container kk">
<br>
<img src="static/photos/no_dp.png" alt="Display image" height='50' width='50'>
<h3 class="name">{{comment.user.username}}</h3>
  <p>{{comment.content}}</p>
</div>
  {%else%}
  <div class="container kk">
  <img src="static/photos/no_dp.png" alt="Display image" height='50' width='50'>
  <h3 class="name">{{comment.user.username}}</h3>
  
    <p>{{comment.content}}</p>
    </div>


{%endif%}
{%endfor%}
{%endmacro%}

app/templates/navbar.html
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
  </head>
  <body class="body" style="background-image:url('')">
    <div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{url_for('main.categories')}}">Categories</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                  {%endif%}
                </ul>
        </div>
  
    </div>
  </div>
  </body>
  </html>

app/templates/pickup.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{%block content%}
<h2>Pickup lines pitches</h2>
{{macro.displayPitches(pitches)}}<br>
{%endblock%}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{{ fontawesome_html() }}
<!-- {% import "bootstrap/wtf.html" as wtf %} -->

<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to 60 seconds pitch</title>
        {% endif %}
      
    {%block content %}
    <div class="block">
    
     {% if pitch.user.profile_pic_path %}
     <div class="container hh">

    <img src="{{ pitch.user.profile_pic_path }}" alt="Display image" height='50'>
    <p class='name'>{{pitch.user.username}}</p>
    
    <h4>{{pitch.content}}</h4>
    <button>Upvote</button>
    <button>Downvote</button>
    <p>Upvotes:{{pitch.upvotes}}</p>
  <p>Downvotes:{{pitch.downvotes}}</p>
  <a href="/new/comment/{{pitch.id}}" class="btn btn-primary">Add comment</a>
    {{macro.displayComments(comments)}}
     </div>

    {%else %}
    <div class="container hh">
    <img src="static/photos/no_dp.png" alt="">
    <p class="name">{{pitch.user.username}}</p>
    <h4>{{pitch.content}}</h4>
    <p>Upvotes:{{pitch.upvotes}}</p>
  <p>Downvotes:{{pitch.downvotes}}</p>
    <button >Upvote</button>
    <button>Downvote</button>
    <a href="/new/comment/{{pitch.id}}" class="btn btn-primary">Add comment</a>
    {{macro.displayComments(comments)}}
</div>
    {%endif%}
    </div>
   {%endblock %}

app/templates/pitches.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">
{{wtf.quick_form(pitch_form)}}

<!-- {{ macro.displayPitches(pitches)}} -->
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
  {% endif %}
  <div class="col-md-4">
        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/promotion.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{%block content%}
<h2>Promotion pitches</h2>
{{macro.displayPitches(pitches)}}<br>
{%endblock%}

app/templates/view_pitch.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
{%block styles%}
 {{ super() }}
{%endblock%}
<!-- content block -->
{% block content %}
<div class="container">
    <div class="col-md-12">
       <p class="text-left"><a class="btn btn-primary" href="{{url_for('.new_pitch',id=pitches.category_id)}}">Post Pitch</a></p>
       <div class="well" style="background-color:lightblue">
         <h3>{{pitches.content}}</h3>
       </div>
       <!-- comments -->
       <div class="col-md-6 col-offset-1">
         <table>
           <tr>
             <td><h4 class="text-left"><a class="btn btn-round" href="{{url_for('.upvote',id=pitches.id)}}">Upvote <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>  </a></h4></td>
             <td>&nbsp;</td>
             <td><h4 class="text-left"><a class="btn btn-round" href="{{url_for('.downvote',id=pitches.id)}}">Downvote <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>  </a></h4></td>
             <td>&nbsp;</td>
             <td><h4 class="text-right">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Comments   <a class="btn btn-primary" href="{{url_for('.post_comment',id=pitches.id)}}"> Add your comment</a></h4></td>
           </tr>
         </table>
        {% if comment %}
        {{ macro.displaySpecificPitch(comment)}}
        <hr>
        {%else%}
        <h3 class="text-center" style="color:orange;">No comments </h3>
        {% endif %}
       </div>
   </div>
 </div>
{% endblock %}